-- Add board_flag column to all post tables
-- Uses a procedure to handle 'column already exists' gracefully on MariaDB 10.1

SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `3` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = '3' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `a` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'a' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `aco` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'aco' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `adv` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'adv' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `an` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'an' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `asp` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'asp' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `b` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'b' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `bant` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'bant' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `biz` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'biz' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `c` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'c' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `cgl` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cgl' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `ck` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'ck' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `cm` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'cm' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `co` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'co' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `d` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'd' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `diy` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'diy' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `e` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'e' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `f` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'f' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `fa` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'fa' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `fit` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'fit' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `g` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'g' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `gd` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'gd' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `gif` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'gif' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `h` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'h' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `hc` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'hc' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `his` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'his' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `hm` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'hm' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `hr` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'hr' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `i` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'i' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `ic` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'ic' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `int` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'int' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `j` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'j' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `jp` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'jp' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `k` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'k' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `lgbt` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'lgbt' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `lit` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'lit' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `m` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'm' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `mlp` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'mlp' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `mu` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'mu' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `n` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'n' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `news` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'news' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `o` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'o' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `out` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'out' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `p` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'p' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `po` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'po' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `pol` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'pol' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `pw` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'pw' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `qa` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'qa' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `qb` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'qb' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `qst` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'qst' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `r` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'r' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `r9k` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'r9k' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `s` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 's' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `s4s` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 's4s' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `sci` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'sci' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `soc` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'soc' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `sp` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'sp' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `t` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 't' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `test` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'test' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `tg` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'tg' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `toy` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'toy' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `trash` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'trash' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `trv` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'trv' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `tv` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'tv' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `u` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'u' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `v` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'v' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `vg` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'vg' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `vip` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'vip' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `vm` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'vm' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `vmg` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'vmg' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `vp` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'vp' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `vr` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'vr' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `vrpg` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'vrpg' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `vst` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'vst' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `vt` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'vt' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `w` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'w' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `wg` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'wg' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `wsg` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'wsg' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `wsr` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'wsr' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `x` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'x' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `xs` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'xs' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
SET @s = (SELECT IF(COUNT(*) = 0, 'ALTER TABLE `y` ADD COLUMN board_flag varchar(16) NOT NULL DEFAULT ""', 'SELECT 1') FROM information_schema.columns WHERE table_schema = DATABASE() AND table_name = 'y' AND column_name = 'board_flag');
PREPARE stmt FROM @s; EXECUTE stmt; DEALLOCATE PREPARE stmt;
